### ISSUE TITLE
Hidden <DependentField> affects the layout

### ISSUE THREAD

**Issue by MaxAlex666** [marmelab/aor-dependent-input#20]
The <DependentField> element if its contents should not be displayed output as an element <div class = "aor-field aor-field-undefined"> <! - react-empty: 148 -> </ div> and break the markup.

**Comment by djhi** [comment]
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/ElxGNxBY0)
* A sample application via GitHub

**Comment by fzaninotto** [comment]
No news for some time, closing.
