### ISSUE TITLE
ReferenceInput

### ISSUE THREAD

**Issue by selini** [marmelab/aor-dependent-input#25]
I have 2 ReferenceInput. The thing I want is to pick a company and  show only branches of that  company. I try this but it does not work.
The branches have a field called motherID that connects them with the companies.

```
    <ReferenceInput  source="CompanyID" reference="companies" allowEmpty alwaysOn>
    <SelectInput optionText={choice => `${choice.name}`} />
    </ReferenceInput>

    <DependentInput dependsOn="CompanyID" >
    <ReferenceInput  source="BranchID" reference="branches" allowEmpty alwaysOn>
    <SelectInput optionText={choice => `${choice.tmima  +" "+ choice.address}`} />
    </ReferenceInput>
    </DependentInput>
```

**Comment by djhi** [comment]
Have you read https://github.com/marmelab/aor-dependent-input#re-rendering-the-dependentinput-children-when-the-values-of-the-dependencies-change ?

Also, please try to put up a repository or, even better, a codesandbox, which reproduce your issue.

Finally, please use StackOverflow when you need help with your code. Github should be kept for issues and feature requests.

**Comment by selini** [comment]
No, I will check it out. 
I posted a question in StackOverflow.  Thanks for the answer. I will close the issue.
