### ISSUE TITLE
DependentInput does not work

### ISSUE THREAD

**Issue by mgomezcuesta** [marmelab/aor-dependent-input#26]
Hi. 

- I am using DependentInput for hide some fields on the scren depending of type of users.
- I have checked differentes configurations but I get unexpected results. No fields are shown

Option 1:
```jsx
import {DependentInput} from 'aor-dependent-input';
<TextField source="type" />
<DependentInput dependsOn="type" value="NATURAL" >
    <TextField source="firstName" />
    <TextField source="lastName" />
</DependentInput>            
<DependentInput dependsOn="type" value="JURIDICAL" >
    <TextField source="companyName" label="Company name"/>
</DependentInput>
```

Option 2:
```jsx
import {DependentInput} from 'aor-dependent-input';
const isNatural = (record) => record.isNatural;
<TextField source="type" />
<DependentInput resolve={isNatural} >
    <TextField source="firstName" />
    <TextField source="lastName" />
</DependentInput>
```

- It show  type set to NATURAL
- I got a undefined error

Option 3:
```jsx
const isNaturalUser = (value) => {value.startsWith('NATURAL');}
<TextField source="type" />
<DependentInput dependsOn="type" resolve={isNaturalUser} >
    <TextField source="firstName" />
    <TextField source="lastName" />
</DependentInput>
```

- It show  type set to NATURAL
- I got a undefined error

![image](https://user-images.githubusercontent.com/43401305/55326362-d60cec00-5487-11e9-851b-9959384afd45.png)

Used Versions:
    "admin-on-rest": "^1.4.1",
    "aor-dependent-input": "^1.2.0",

Could anyone help me? 

Thanks you very much.

**Comment by djhi** [comment]
If you are able to illustrate the bug or feature request with an example, please provide a sample application via one of the following means:

* CodeSandbox (https://codesandbox.io/s/ywwkr0327z)
* A sample application via GitHub

**Comment by fzaninotto** [comment]
Note that aor-dependent-input is deprecated. In react-admin (successor to admin-on-rest), dependent inputs are implemented with the FormDataConsumer component.

**Comment by mgomezcuesta** [comment]
Thanks so much. I have to check with FormDataConsumer component.
